plugins {
    id 'java'
    id 'war'
}

group = 'ru.itis'
version = '1.0-SNAPSHOT'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(22) }
}

repositories { mavenCentral() }

dependencies {
    implementation 'jakarta.platform:jakarta.jakartaee-web-api:10.0.0'

    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'
    implementation 'org.postgresql:postgresql:42.7.7'
    implementation 'org.mindrot:jbcrypt:0.4'

    compileOnly 'org.projectlombok:lombok:1.18.40'
    annotationProcessor 'org.projectlombok:lombok:1.18.40'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test { useJUnitPlatform() }